name: swear_counter_app
description: A Flutter app that counts swear words using microphone input and an LLM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  speech_to_text: ^6.3.0
  shared_preferences: ^2.2.2
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env

